"use client";
import {useEffect,useRef,useState} from "react";

type RecordItem={id:string;title:string;docketId:string|null;documentType:string;postedDate:string|null;commentEndDate:string|null;openForComment:boolean;frDocNum:string|null;regulationsUrl:string;docketUrl:string|null};
type Selected=RecordItem&{retrievedAt:string;query:string;scope:"year"|"all";source:string;fromDate:string|null;toDate:string};
type SearchResult={query:string;agency:string;scope:"year"|"all";source:string;retrievedAt:string;fromDate:string|null;toDate:string;page:number;totalElements:number;totalPages:number;hasNextPage:boolean;coverageLimit:string;records:RecordItem[]};
type OverviewData={source:string;retrievedAt:string;fromDate:string;toDate:string;totalElements:number;recordsReturned:number;complete:boolean;docketCount:number|null;typeAggregation:{label:string;count:number}[];cadence:{month:string;count:number}[];latest:RecordItem[];coverage:string};
type CommentData={docketId:string;source:string;retrievedAt:string;page:number;totalElements:number;totalPages:number;hasNextPage:boolean;coverageLimit:string;comments:{id:string;title:string;postedDate:string|null;withdrawn:boolean;url:string}[]};
const nav=["Live search","Overview","Regulation","Submissions","Issues","Draft response","QA & record","How it works"];
const fmt=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00Z`).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"});
const scopeLabel=(from:string|null,to:string)=>from?`rolling ${fmt(from)}–${fmt(to)}`:`all available CPSC records through ${fmt(to)}`;
const need=<section className="page-view"><div className="live-state"><h2>Select an official record first</h2><p>Run Live search and choose “Use in workspace.” Record-specific panels remain empty until an authoritative result is selected.</p></div></section>;

export default function Home(){
 const [view,setView]=useState("Live search"),[record,setRecord]=useState<Selected|null>(null);
 const clear=()=>setRecord(null);
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="seal">C</span><div><strong>REGULATORY REVIEW</strong><small>Live CPSC public-source workspace</small></div></div><div className="docket-title"><span className="eyebrow">DEFAULT ROLLING 12-MONTH SCOPE</span><span>{record?record.title:"CPSC regulatory records"}</span></div><div className="top-actions"><a className="method-link" href="/CPSC_Regulatory_Analysis_Foundry_Methodology.docx" download>Methodology ↓</a><button className="how-button" onClick={()=>setView("How it works")}>How it works</button></div></header>
 <div className="truth-banner"><strong>Official live records</strong><span>Default search and dashboard cover the rolling prior 12 months. Choose “All available CPSC records” for older topics. Exact scope is shown with every retrieval.</span></div>
 <div className="casebar"><div><span className="live-dot"/>{record?`Active: ${record.id}`:"No active record selected"}</div><div className="case-stats"><span>Source: <b>Regulations.gov API v4</b></span>{record&&<button className="clear-record" onClick={clear}>Clear active record</button>}</div></div>
 <nav className="tabs">{nav.map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}>{x}</button>)}</nav>
 {view==="Live search"&&<LiveSearch selected={record} onSelect={x=>{setRecord(x);setView("Overview")}} onClear={clear}/>} {view==="Overview"&&<ExecutiveOverview record={record} setView={setView}/>} {view==="Regulation"&&<Regulation record={record}/>} {view==="Submissions"&&<Submissions record={record}/>} {view==="Issues"&&<Issues record={record}/>} {view==="Draft response"&&<Draft record={record}/>} {view==="QA & record"&&<QA record={record}/>} {view==="How it works"&&<><Guide setView={setView}/><div className="guide-download"><strong>Detailed methodology and controls</strong><span>Download the public Regulatory Analysis Foundry methodology Word document.</span><a href="/CPSC_Regulatory_Analysis_Foundry_Methodology.docx" download>Download methodology (.docx) ↓</a></div></>}</main>
}

function LiveSearch({selected,onSelect,onClear}:{selected:Selected|null;onSelect:(x:Selected)=>void;onClear:()=>void}){
 const [term,setTerm]=useState("burden reduction"),[scope,setScope]=useState<"year"|"all">("year"),[result,setResult]=useState<SearchResult|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const resultAnchor=useRef<HTMLDivElement>(null);
 const run=async(page=1)=>{setLoading(true);setError("");setResult(null);onClear();try{const r=await fetch(`/api/search?q=${encodeURIComponent(term.trim())}&scope=${scope}&page=${page}`,{cache:"no-store"}),x=await r.json();if(!r.ok)throw new Error(x.error);setResult(x);setTimeout(()=>resultAnchor.current?.scrollIntoView({behavior:"smooth",block:"start"}),50)}catch(e){setResult(null);setError(e instanceof Error?e.message:"Search failed");setTimeout(()=>resultAnchor.current?.scrollIntoView({behavior:"smooth",block:"start"}),50)}finally{setLoading(false)}};
 return <section className="live-view"><div className="live-hero"><span className="eyebrow">LIVE OFFICIAL-SOURCE SEARCH</span><h1>Search CPSC regulatory records</h1><p>Defaults to documents posted within the <b>rolling 12 months ending at retrieval</b>. Choose the historical scope to query all available CPSC document records without a posted-date filter.</p>{selected&&<div className="active-record"><strong>Active record</strong><span>{selected.title}</span><button onClick={onClear}>Clear</button></div>}<form onSubmit={e=>{e.preventDefault();run(1)}}><input aria-label="CPSC topic or regulation term" value={term} onChange={e=>setTerm(e.target.value)} minLength={2} maxLength={80}/><select aria-label="Search scope" value={scope} onChange={e=>{setScope(e.target.value as "year"|"all");setResult(null);onClear()}}><option value="year">Rolling past 12 months</option><option value="all">All available CPSC records</option></select><button disabled={loading}>{loading?"Searching…":"Search official records"}</button></form><div className="scope-strip"><strong>Selected scope</strong><span>{scope==="year"?"CPSC documents · rolling prior 12 months":"CPSC documents · all available dates · no posted-date filter"} · 20 results/page · first 5 pages maximum</span></div><div className={`search-feedback ${error?"failed":""}`} role="status" aria-live="polite">{loading?`Searching the official CPSC record for “${term.trim()}”…`:error?"Search failed; details are shown below.":result?`${result.totalElements} official API match${result.totalElements===1?"":"es"} loaded below for “${result.query}” in ${result.scope==="all"?"all available records":"the rolling 12-month window"}.`:"Results will appear directly below and the page will move to them."}</div></div><div ref={resultAnchor} className="result-anchor" tabIndex={-1}/>
 {error&&<State title="Official-source search unavailable" text={`${error} No cached or sample results were substituted.`}/>} {!result&&!error&&!loading&&<State title="Ready to search" text="Enter a topic, product, rule, docket term, or regulation phrase."/>}
 {result&&<><Meta result={result}/>{result.records.length===0?<State title="No matching CPSC documents in the selected scope" text={`No records matched “${result.query}” in ${scopeLabel(result.fromDate,result.toDate)}. Try “All available CPSC records” for an older topic.`}/>:<div className="result-list">{result.records.map(x=><article key={x.id}><div className="result-meta"><span>{x.documentType}</span><span>Posted {x.postedDate?fmt(x.postedDate):"unavailable"}</span>{x.openForComment&&<em>Open for comment</em>}</div><h2>{x.title}</h2><p>{x.id}{x.docketId&&` · Docket ${x.docketId}`}</p><div className="result-actions"><button onClick={()=>onSelect({...x,retrievedAt:result.retrievedAt,query:result.query,scope:result.scope,source:result.source,fromDate:result.fromDate,toDate:result.toDate})}>Use in workspace →</button><a href={x.regulationsUrl} target="_blank">Official document ↗</a>{x.docketUrl&&<a href={x.docketUrl} target="_blank">Docket ↗</a>}</div></article>)}</div>}<div className="pagination"><button disabled={result.page<=1||loading} onClick={()=>run(result.page-1)}>← Previous</button><span>Page {result.page} of {Math.max(1,result.totalPages)} within workspace limit</span><button disabled={!result.hasNextPage||loading} onClick={()=>run(result.page+1)}>Next →</button></div><p className="provenance-note"><b>Source:</b> {result.source}. Query “{result.query}”; CPSC only; {scopeLabel(result.fromDate,result.toDate)}. Search terms are applied by the official API across its indexed document record; a match need not appear in the displayed title. Only actual API-returned records are shown.</p></>}
 </section>
}
function Meta({result}:{result:SearchResult}){return <div className="retrieval-bar"><div><strong>{result.totalElements.toLocaleString()}</strong><span>official API matches</span></div><div><span>Selected scope</span><strong>{scopeLabel(result.fromDate,result.toDate)}</strong></div><div><span>Retrieved</span><strong>{new Date(result.retrievedAt).toLocaleString()}</strong></div><div><span>Coverage</span><strong>{result.coverageLimit}</strong></div></div>}
function State({title,text}:{title:string;text:string}){return <div className="live-state"><h2>{title}</h2><p>{text}</p></div>}

function ExecutiveOverview({record,setView}:{record:Selected|null;setView:(x:string)=>void}){
 const [data,setData]=useState<OverviewData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/overview",{cache:"no-store"}),x=await r.json();if(!r.ok)throw new Error(x.error);setData(x)}catch(e){setData(null);setError(e instanceof Error?e.message:"Overview failed")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 return <section className="page-view executive"><div className="page-intro"><span className="eyebrow">EXECUTIVE OVERVIEW · LIVE ROLLING 12-MONTH CPSC RECORD</span><h1>{data?`${data.totalElements.toLocaleString()} CPSC document records posted in the rolling 12-month window`:"Recent CPSC regulatory activity"}</h1><p>Official-source activity only. Counts and categories are reported or calculated from the bounded Regulations.gov response; no policy interpretation is added.</p></div>{loading&&<State title="Refreshing official overview" text="Retrieving the current rolling 12-month CPSC record…"/>}{error&&<State title="Overview unavailable" text={`${error} No stored figures were substituted.`}/>} {data&&<><div className="metric-grid"><article><strong>{data.totalElements}</strong><span>verified in-scope document records</span></article><article><strong>{data.docketCount??"—"}</strong><span>{data.docketCount===null?"unique docket count withheld because returned records are incomplete":"unique dockets represented"}</span></article><article><strong>{fmt(data.fromDate)}</strong><span>window start; ending {fmt(data.toDate)}</span></article></div><div className="overview-grid"><article className="feature-card"><span className="section-label">RECORD TYPES</span><h2>Official API categories</h2>{data.typeAggregation.slice(0,6).map(x=><div className="breakdown" key={x.label}><span>{x.label}</span><strong>{x.count}</strong></div>)}</article><article className="feature-card"><span className="section-label">POSTING CADENCE</span><h2>Records by month</h2>{data.complete?data.cadence.map(x=><div className="breakdown" key={x.month}><span>{x.month}</span><strong>{x.count}</strong></div>):<p>Withheld because the returned record set is incomplete.</p>}</article></div><div className="latest-records"><span className="section-label">LATEST OFFICIAL ENTRIES</span>{data.latest.map(x=><article key={x.id}><div><small>{x.documentType} · {x.postedDate?fmt(x.postedDate):"date unavailable"}</small><h2>{x.title}</h2></div><a href={x.regulationsUrl} target="_blank">Open ↗</a></article>)}</div><p className="provenance-note"><b>Scope:</b> CPSC documents posted {fmt(data.fromDate)}–{fmt(data.toDate)}. <b>Retrieved:</b> {new Date(data.retrievedAt).toLocaleString()}. <b>Source:</b> {data.source}. {data.coverage}</p></>}{record&&<div className="active-record overview-active"><strong>Selected record</strong><span>{record.title}</span><button onClick={()=>setView("Regulation")}>Open record →</button></div>}<button className="refresh" onClick={load} disabled={loading}>Refresh overview</button></section>
}

function Regulation({record}:{record:Selected|null}){if(!record)return need;return <section className="page-view"><div className="page-intro"><span className="eyebrow">SELECTED OFFICIAL RECORD</span><h1>{record.title}</h1><p>Metadata returned for the selected Regulations.gov document. This panel does not infer legal effect or summarize unseen document text.</p></div><div className="record-grid"><article><span>Document ID</span><strong>{record.id}</strong><small>{record.documentType}</small></article><article><span>Docket</span><strong>{record.docketId||"Not provided"}</strong><small>Agency CPSC</small></article><article><span>Posted</span><strong>{record.postedDate?fmt(record.postedDate):"Unavailable"}</strong><small>{record.openForComment?"Open for comment":"Not shown as open for comment"}</small></article></div><div className="source-callout"><h2>Provenance</h2><p>Selected from query “{record.query}” within {scopeLabel(record.fromDate,record.toDate)}. Retrieved {new Date(record.retrievedAt).toLocaleString()} from {record.source}.</p><div className="source-actions"><a href={record.regulationsUrl} target="_blank">Official document ↗</a>{record.docketUrl&&<a href={record.docketUrl} target="_blank">Official docket ↗</a>}</div></div></section>}

function Submissions({record}:{record:Selected|null}){
 const [data,setData]=useState<CommentData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const load=async(page=1)=>{if(!record?.docketId)return;setLoading(true);setError("");setData(null);try{const r=await fetch(`/api/comments?docketId=${encodeURIComponent(record.docketId)}&page=${page}`,{cache:"no-store"}),x=await r.json();if(!r.ok)throw new Error(x.error);setData(x)}catch(e){setError(e instanceof Error?e.message:"Comment lookup failed")}finally{setLoading(false)}};
 useEffect(()=>{setData(null);setError("");if(record?.docketId)load(1)},[record?.id]);
 if(!record)return need;if(!record.docketId)return <section className="page-view"><State title="No docket available for this record" text="The official document metadata did not provide a docket ID, so no comment query was attempted."/></section>;
 return <section className="page-view"><div className="page-intro"><span className="eyebrow">LIVE PUBLIC COMMENTS</span><h1>Submissions for {record.docketId}</h1><p>Real public comment records from the Regulations.gov comments endpoint. No sample submissions appear here.</p></div>{loading&&<State title="Retrieving comments" text="Querying the selected official docket…"/>}{error&&<State title="Comments unavailable" text={error}/>} {data&&<>{data.comments.length===0?<State title="No public comments returned" text="The official comments endpoint returned no records for this docket at retrieval time."/>:<div className="submission-table">{data.comments.map(x=><a className="submission-row" href={x.url} target="_blank" key={x.id}><span className="doc-icon">▤</span><div><strong>{x.title}</strong><small>{x.id} · {x.postedDate?fmt(x.postedDate):"date unavailable"}</small></div><span>↗</span></a>)}</div>}<div className="pagination"><button disabled={data.page<=1} onClick={()=>load(data.page-1)}>← Previous</button><span>Page {data.page} of {Math.max(1,data.totalPages)} · {data.totalElements} reported comments</span><button disabled={!data.hasNextPage} onClick={()=>load(data.page+1)}>Next →</button></div><p className="provenance-note">Source: {data.source}. Retrieved {new Date(data.retrievedAt).toLocaleString()}. {data.coverageLimit}</p></>}</section>
}

function Issues({record}:{record:Selected|null}){if(!record)return need;return <section className="page-view"><div className="page-intro"><span className="eyebrow">LIVE EVIDENCE AVAILABILITY</span><h1>Automated issue analysis is not available for this record</h1><p>The live source path retrieved document metadata and official pointers, but it has not retrieved and validated sufficient full text, attachments, and comment passages to produce defensible topics or issues.</p></div><div className="source-callout"><h2>Verified evidence currently available</h2><div className="breakdown"><span>Title</span><strong>{record.title}</strong></div><div className="breakdown"><span>Document type</span><strong>{record.documentType}</strong></div><div className="breakdown"><span>Docket</span><strong>{record.docketId||"Not provided"}</strong></div><div className="breakdown"><span>Posted</span><strong>{record.postedDate?fmt(record.postedDate):"Unavailable"}</strong></div><p>No topic model, stance, confidence score, or recommended issue is inferred from metadata alone.</p><a className="source-link" href={record.regulationsUrl} target="_blank">Review official source ↗</a></div><p className="provenance-note">Retrieved {new Date(record.retrievedAt).toLocaleString()} from {record.source}; scope: {scopeLabel(record.fromDate,record.toDate)}.</p></section>}

function Draft({record}:{record:Selected|null}){const key=record?`cpsc-human-draft-${record.id}`:"",[text,setText]=useState("");useEffect(()=>{setText(key?localStorage.getItem(key)||"":"")},[key]);if(!record)return need;return <section className="page-view"><div className="page-intro"><span className="eyebrow">EMPTY HUMAN-AUTHORED WORKSPACE</span><h1>Notes for {record.id}</h1><p>No response was generated from the live record. Anything entered below is authored by the person using this browser and saved on this device only.</p></div><textarea className="human-draft" value={text} onChange={e=>{setText(e.target.value);localStorage.setItem(key,e.target.value)}} placeholder="Write human-authored notes or a draft here…"/><div className="guardrail wide"><span>!</span><p><strong>Not legal advice or agency work product</strong>This text is not source-grounded or approved merely because it is stored beside an official record. Validate evidence, authority, and policy through authorized review.</p></div></section>}

function QA({record}:{record:Selected|null}){return <section className="page-view"><div className="page-intro"><span className="eyebrow">QUALITY & RECORD</span><h1>Live capability boundaries</h1><p>{record?`Current record: ${record.id}.`:"No record selected."} The dashboard uses a rolling 12-month boundary; search also offers an explicit all-available historical scope.</p></div><div className="qa-grid"><article><span className="qa-state good">LIVE NOW</span><h2>Official source functions</h2><ul><li>Independent rolling 12-month executive overview</li><li>12-month or all-available CPSC document search</li><li>Selected-record metadata and official links</li><li>Selected-docket public comment pagination</li></ul></article><article><span className="qa-state warn">NOT AVAILABLE</span><h2>Analysis and governance</h2><ul><li>No validated full-text/attachment evidence pipeline</li><li>No automated issues, positions, or recommendations</li><li>No database, audit log, agents, or Temporal workflow</li><li>No agency approval or legal determination</li></ul></article></div></section>}

function Guide({setView}:{setView:(x:string)=>void}){const steps=[["1","Refresh the executive overview","Overview independently queries CPSC documents posted during the rolling 12 months ending at retrieval. It reports official totals and supported breakdowns."],["2","Choose a search scope","Live search defaults to the same rolling 12-month CPSC window. For an older topic, choose “All available CPSC records”; that query omits the posted-date filter and states the broader scope."],["3","Select an official record","Selection drives Overview context, Regulation metadata, Submissions, Issues availability, Draft response, and QA. A new query, scope change, or Clear removes stale selection."],["4","Retrieve docket comments","When the selected metadata includes a CPSC docket ID, Submissions queries the official comments endpoint with pagination. Empty and failure states never substitute samples."],["5","Respect the evidence boundary","Issues reports only verified metadata and source pointers. Without sufficient validated text, it explicitly withholds automated topics and recommendations."],["6","Keep drafting human-authored","Draft response begins empty, is tied to the selected document ID, and saves only in the current browser. It is not agency work product or legal advice."]];const [step,setStep]=useState(0),s=steps[step];return <section className="guide-view"><div className="guide-hero"><div><span className="eyebrow">CURRENT LIVE OPERATING FLOW</span><h1>From an official CPSC query to source review</h1><p>This is what the public workspace actually does now—without sample issues or synthetic recommendations.</p></div><div className="prototype-stamp"><strong>Exact live scope</strong><span>Default: rolling prior 12 months. Optional: all available CPSC document records with no posted-date filter.</span></div></div><div className="guide-layout"><ol className="guide-steps">{steps.map((x,i)=><li key={x[0]}><button className={i===step?"active":""} onClick={()=>setStep(i)}><span>{x[0]}</span>{x[1]}</button></li>)}</ol><article className="guide-card"><span className="guide-number">STEP {s[0]} OF 6</span><h2>{s[1]}</h2><p>{s[2]}</p><div className="guide-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button>{step<5?<button className="primary" onClick={()=>setStep(step+1)}>Next</button>:<button className="primary" onClick={()=>setView("Live search")}>Start live search</button>}</div></article></div></section>}
