import {NextRequest,NextResponse} from "next/server";

const ALGORITHM="cpsc-comment-issue-matrix/2.0.0",HAZARD_TAXONOMY_VERSION="cpsc-comment-hazard-domains/2.0.0",LISTING_PAGE_SIZE=250,MAX_LISTING_PAGES=40,MAX_DETAIL_REQUESTS=250,DETAIL_CONCURRENCY=6,CACHE_TTL_MS=15*60_000,MAX_RETRIES=3;
const TAXONOMY=[
 {label:"Regulatory burden and cost",words:["burden","cost","expense","paperwork","duplicat","economic"]},{label:"Consumer safety and risk",words:["safety","risk","hazard","injur","death","protect"]},{label:"Compliance, testing, and certification",words:["compliance","test","certif","enforce","standard","requirement"]},{label:"Small entities and market effects",words:["small business","small entit","manufacturer","retailer","importer","market"]},{label:"Regulatory clarity and process",words:["clarity","guidance","interpret","definition","process","procedure","deadline"]},{label:"Evidence and data",words:["data","evidence","study","analysis","estimate","research"]},{label:"Innovation, competition, and consumer choice",words:["innovation","competition","choice","technology","entrant","design"]},
];
const HAZARD_DOMAINS=[
 {label:"Electrical",patterns:[/\belectr(?:ic|ical|ocution)\w*\b/gi,/\bshock\w*\b/gi,/\bbatter(?:y|ies)\b/gi,/\bvoltage\b/gi,/\bwiring\b/gi,/\bcharger\w*\b/gi]},{label:"Mechanical",patterns:[/\bmechanical\b/gi,/\bmoving parts?\b/gi,/\bstructural\b/gi,/\bbreakage\b/gi,/\bcrush\w*\b/gi,/\bpinch\w*\b/gi,/\bimpact\w*\b/gi]},{label:"Thermal",patterns:[/\bthermal\b/gi,/\btemperature\w*\b/gi,/\boverheat\w*\b/gi,/\bhot surfaces?\b/gi,/\bburn(?:s|ed|ing)?\b/gi,/\bscald\w*\b/gi]},{label:"Chemical",patterns:[/\bchemical\w*\b/gi,/\bcorrosive\w*\b/gi,/\bsolvent\w*\b/gi,/\bacid\w*\b/gi,/\balkali\w*\b/gi,/\bleak(?:s|ed|ing|age)?\b/gi]},{label:"Fire/Explosion",patterns:[/\bfires?\b/gi,/\bflames?\b/gi,/\bflammab\w*\b/gi,/\bcombust\w*\b/gi,/\bignit\w*\b/gi,/\bexplod\w*\b/gi,/\bexplosion\w*\b/gi,/\bblast\w*\b/gi]},{label:"Choking/Ingestion",patterns:[/\bchok\w*\b/gi,/\bingest\w*\b/gi,/\bswallow\w*\b/gi,/\bsmall parts?\b/gi,/\baspirat\w*\b/gi]},{label:"Laceration",patterns:[/\blacerat\w*\b/gi,/\bcuts?\b/gi,/\bsharp edges?\b/gi,/\bpunctur\w*\b/gi,/\bblades?\b/gi]},{label:"Fall/Tip-over",patterns:[/\bfalls?\b/gi,/\btip[- ]over\b/gi,/\btipping\b/gi,/\bunstable\b/gi,/\brollover\b/gi]},{label:"Entrapment/Strangulation",patterns:[/\bentrap\w*\b/gi,/\bstrang\w*\b/gi,/\bsuffocat\w*\b/gi,/\bcords?\b/gi,/\bwedg\w*\b/gi,/\bpinning\b/gi]},{label:"Toxicological",patterns:[/\btoxic\w*\b/gi,/\bpoison\w*\b/gi,/\bcarcinogen\w*\b/gi,/\blead(?: exposure| content| poisoning| paint)?\b/gi,/\bphthalate\w*\b/gi,/\binhalation\b/gi]},{label:"Labeling/Instruction",patterns:[/\blabel\w*\b/gi,/\bwarnings?\b/gi,/\binstructions?\b/gi,/\bmanuals?\b/gi,/\bdisclosures?\b/gi,/\bmarkings?\b/gi]},
];
const clean=(v:unknown)=>typeof v==="string"?v.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim():"";
const hazardResult=(text:string)=>{const matches=HAZARD_DOMAINS.map(d=>({tag:d.label,terms:[...new Set(d.patterns.flatMap(p=>text.match(p)||[]).map(x=>x.toLowerCase()))]})).filter(x=>x.terms.length);return matches.length?{hazardTags:matches.map(x=>x.tag),hazardBasis:matches}:{hazardTags:["Unclear/Needs review"],hazardBasis:[]}};
const apiKey=()=>process.env.REGULATIONS_GOV_API_KEY||"DEMO_KEY";
class UpstreamError extends Error{status:number;constructor(status:number){super(`Official Regulations.gov API returned ${status}`);this.status=status}}
const responseCache=new Map<string,{at:number;value:any}>(),inFlight=new Map<string,Promise<any>>(),wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function getJson(url:string){const cached=responseCache.get(url);if(cached&&Date.now()-cached.at<CACHE_TTL_MS)return cached.value;const active=inFlight.get(url);if(active)return active;const work=(async()=>{for(let attempt=0;attempt<=MAX_RETRIES;attempt++){const r=await fetch(url,{headers:{Accept:"application/vnd.api+json","User-Agent":"CPSC-Regulatory-Review-Workspace/2.0"},cache:"no-store",signal:AbortSignal.timeout(15_000)});if(r.ok){const value=await r.json();responseCache.set(url,{at:Date.now(),value});return value}if(!(r.status===429||r.status>=500)||attempt===MAX_RETRIES)throw new UpstreamError(r.status);const retryAfter=Number(r.headers.get("Retry-After"));await wait(Number.isFinite(retryAfter)&&retryAfter>0?retryAfter*1000:400*(2**attempt)+Math.floor(Math.random()*200))}throw new UpstreamError(502)})();inFlight.set(url,work);try{return await work}finally{inFlight.delete(url)}}
async function getListings(docketId:string,key:string){const listed:any[]=[];let meta:any={};for(let page=1;page<=MAX_LISTING_PAGES;page++){const params=new URLSearchParams({"filter[docketId]":docketId,"page[number]":String(page),"page[size]":String(LISTING_PAGE_SIZE),sort:"-postedDate",api_key:key}),payload=await getJson(`https://api.regulations.gov/v4/comments?${params}`);listed.push(...(payload.data||[]));meta=payload.meta||meta;if(!meta.hasNextPage||page>=Number(meta.totalPages||1))break}return {listed:[...new Map(listed.map(x=>[x.id,x])).values()],meta}}
async function getDetails(items:any[],key:string){const results:any[]=[];for(let i=0;i<items.length;i+=DETAIL_CONCURRENCY)results.push(...await Promise.all(items.slice(i,i+DETAIL_CONCURRENCY).map(async item=>{try{return {item:(await getJson(`https://api.regulations.gov/v4/comments/${encodeURIComponent(item.id)}?api_key=${encodeURIComponent(key)}`)).data,detailRetrieved:true,detailStatus:null}}catch(e){return {item,detailRetrieved:false,detailStatus:e instanceof UpstreamError?e.status:null}}})));return results}

export async function GET(request:NextRequest){
 const docketId=(request.nextUrl.searchParams.get("docketId")||"").trim(),documentId=(request.nextUrl.searchParams.get("documentId")||"").trim();
 if(!/^CPSC-[A-Z0-9-]{4,40}$/i.test(docketId))return NextResponse.json({error:"A valid selected CPSC docket ID is required."},{status:422});
 const retrievedAt=new Date().toISOString(),key=apiKey();
 try{
  const {listed,meta}=await getListings(docketId,key),nonWithdrawn=listed.filter((x:any)=>!x.attributes?.withdrawn),details=await getDetails(nonWithdrawn.slice(0,MAX_DETAIL_REQUESTS),key),detailById=new Map(details.map(x=>[x.item.id,x]));
  const comments=nonWithdrawn.map((listing:any)=>{const detail:any=detailById.get(listing.id),item=detail?.item||listing,a=item.attributes||{},text=clean(a.comment),lower=text.toLowerCase(),themeTags=TAXONOMY.filter(t=>t.words.some(w=>lower.includes(w))).map(t=>t.label),hazard=text?hazardResult(text):{hazardTags:["Unclear/Needs review"],hazardBasis:[]},first=clean(a.firstName),last=clean(a.lastName),organization=clean(a.organization);return {id:item.id,postedDate:a.postedDate||null,title:clean(a.title)||"Public comment",submitterName:[first,last].filter(Boolean).join(" ")||null,organization:organization||null,submitterAvailability:first||last||organization?"published":"unavailable_or_redacted",textAvailable:Boolean(text),textStatus:text?"available":detail?"unavailable_from_official_detail":"detail_not_retrieved",excerpt:text?text.slice(0,520):"Comment text was not available in the retrieved official record.",sourceUrl:`https://www.regulations.gov/comment/${encodeURIComponent(item.id)}`,detailRetrieved:Boolean(detail?.detailRetrieved),detailStatus:detail?.detailStatus??null,themeTags:themeTags.length?themeTags:["Other / no theme match"],hazardTags:hazard.hazardTags,hazardBasis:hazard.hazardBasis}});
  const themeLabels=[...TAXONOMY.map(x=>x.label),"Other / no theme match"],themes=themeLabels.map(theme=>{const matching=comments.filter(c=>c.themeTags.includes(theme));return {theme,count:matching.length,commentIds:matching.map(c=>c.id),humanReviewStatus:"unreviewed"}}).filter(x=>x.count).sort((a,b)=>b.count-a.count||a.theme.localeCompare(b.theme)),domainAggregation=[...new Set(comments.flatMap(c=>c.hazardTags))].map(domain=>({domain,count:comments.filter(c=>c.hazardTags.includes(domain)).length})).sort((a,b)=>b.count-a.count||a.domain.localeCompare(b.domain));
  const total=meta.totalElements??listed.length,listingComplete=listed.length>=total;
  return NextResponse.json({documentId,docketId,retrievedAt,source:"Regulations.gov API v4 — complete docket listing plus comment-detail endpoints",credentialMode:process.env.REGULATIONS_GOV_API_KEY?"configured_server_key":"shared_public_demo_key",algorithm:ALGORITHM,hazardTaxonomyVersion:HAZARD_TAXONOMY_VERSION,method:"Every non-withdrawn comment returned by the official docket listing is retained as a matrix row. Hazard domains are assigned independently to each comment from that comment's accessible text; domain and theme totals are calculated only afterward. Comments without a keyword theme remain under Other / no theme match, and comments without accessible text remain visible as Unclear/Needs review.",totalCommentsReported:total,commentsListed:listed.length,listingComplete,commentsDetailed:details.length,detailRetrievedCount:details.filter(x=>x.detailRetrieved).length,detailUnavailableCount:details.filter(x=>!x.detailRetrieved).length,detailRateLimitedCount:details.filter(x=>x.detailStatus===429).length,detailLimit:MAX_DETAIL_REQUESTS,textAvailableCount:comments.filter(c=>c.textAvailable).length,submitterUnavailableCount:comments.filter(c=>c.submitterAvailability!=="published").length,unclassifiedTextComments:comments.filter(c=>c.textAvailable&&c.themeTags.includes("Other / no theme match")).length,themes,domainAggregation,comments,limitations:`The official API listing reported ${total} comments and returned ${listed.length} unique records${listingComplete?" (complete)":" (official listing coverage incomplete)"}. All returned non-withdrawn records remain visible. Text detail is requested for up to ${MAX_DETAIL_REQUESTS} newest non-withdrawn comments per run; attachments, private fields, and withdrawn comments are not analyzed. Missing text is never silently dropped. Tags and aggregates are deterministic screening aids requiring human review, not agency findings or legal conclusions.`},{headers:{"Cache-Control":"no-store"}});
 }catch(e){const status=e instanceof UpstreamError&&e.status===429?429:502;return NextResponse.json({error:`Public comments could not be retrieved from Regulations.gov. ${e instanceof Error?e.message:"Official service unavailable"}. No substitute data was used.`,documentId,docketId,retrievedAt,algorithm:ALGORITHM},{status,headers:status===429?{"Retry-After":"60"}:undefined})}
}
