import {NextRequest,NextResponse} from "next/server";
const ALGORITHM="cpsc-comment-theme-matrix/1.3.0",HAZARD_TAXONOMY_VERSION="cpsc-hazard-domain-tags/1.1.0",MAX_COMMENT_DETAILS=50,LISTING_PAGE_SIZE=50,MAX_LISTING_PAGES=10,DETAIL_INTERVAL_MS=1100,CACHE_TTL_MS=15*60_000,MAX_RETRIES=3;
const TAXONOMY=[
 {label:"Regulatory burden and cost",words:["burden","cost","expense","paperwork","duplicat","economic"]},
 {label:"Consumer safety and risk",words:["safety","risk","hazard","injur","death","protect"]},
 {label:"Compliance, testing, and certification",words:["compliance","test","certif","enforce","standard","requirement"]},
 {label:"Small entities and market effects",words:["small business","small entit","manufacturer","retailer","importer","market"]},
 {label:"Regulatory clarity and process",words:["clarity","guidance","interpret","definition","process","procedure","deadline"]},
 {label:"Evidence and data",words:["data","evidence","study","analysis","estimate","research"]},
 {label:"Innovation, competition, and consumer choice",words:["innovation","competition","choice","technology","entrant","design"]},
];
const HAZARD_DOMAINS=[
 {label:"Electrical",patterns:[/\belectr(?:ic|ical|ocution)\w*\b/gi,/\bshock\w*\b/gi,/\bbatter(?:y|ies)\b/gi,/\bvoltage\b/gi,/\bwiring\b/gi,/\bcharger\w*\b/gi]},
 {label:"Mechanical",patterns:[/\bmechanical\b/gi,/\bmoving parts?\b/gi,/\bstructural\b/gi,/\bbreakage\b/gi,/\bcrush\w*\b/gi,/\bpinch\w*\b/gi,/\bimpact\w*\b/gi]},
 {label:"Thermal",patterns:[/\bthermal\b/gi,/\btemperature\w*\b/gi,/\boverheat\w*\b/gi,/\bhot surfaces?\b/gi,/\bburn(?:s|ed|ing)?\b/gi,/\bscald\w*\b/gi]},
 {label:"Chemical",patterns:[/\bchemical\w*\b/gi,/\bcorrosive\w*\b/gi,/\bsolvent\w*\b/gi,/\bacid\w*\b/gi,/\balkali\w*\b/gi,/\bleak(?:s|ed|ing|age)?\b/gi]},
 {label:"Fire/Explosion",patterns:[/\bfires?\b/gi,/\bflames?\b/gi,/\bflammab\w*\b/gi,/\bcombust\w*\b/gi,/\bignit\w*\b/gi,/\bexplod\w*\b/gi,/\bexplosion\w*\b/gi,/\bblast\w*\b/gi]},
 {label:"Choking/Ingestion",patterns:[/\bchok\w*\b/gi,/\bingest\w*\b/gi,/\bswallow\w*\b/gi,/\bsmall parts?\b/gi,/\baspirat\w*\b/gi]},
 {label:"Laceration",patterns:[/\blacerat\w*\b/gi,/\bcuts?\b/gi,/\bsharp edges?\b/gi,/\bpunctur\w*\b/gi,/\bblades?\b/gi]},
 {label:"Fall/Tip-over",patterns:[/\bfalls?\b/gi,/\btip[- ]over\b/gi,/\btipping\b/gi,/\bunstable\b/gi,/\brollover\b/gi]},
 {label:"Entrapment/Strangulation",patterns:[/\bentrap\w*\b/gi,/\bstrang\w*\b/gi,/\bsuffocat\w*\b/gi,/\bcords?\b/gi,/\bwedg\w*\b/gi,/\bpinning\b/gi]},
 {label:"Toxicological",patterns:[/\btoxic\w*\b/gi,/\bpoison\w*\b/gi,/\bcarcinogen\w*\b/gi,/\blead(?: exposure| content| poisoning| paint)?\b/gi,/\bphthalate\w*\b/gi,/\binhalation\b/gi]},
 {label:"Labeling/Instruction",patterns:[/\blabel\w*\b/gi,/\bwarnings?\b/gi,/\binstructions?\b/gi,/\bmanuals?\b/gi,/\bdisclosures?\b/gi,/\bmarkings?\b/gi]},
];
const hazardResult=(evidence:string)=>{const matches=HAZARD_DOMAINS.map(d=>({tag:d.label,terms:[...new Set(d.patterns.flatMap(p=>evidence.match(p)||[]).map(x=>x.toLowerCase()))]})).filter(x=>x.terms.length);return matches.length?{hazardTags:matches.map(x=>x.tag),hazardBasis:matches}:{hazardTags:["Unclear/Needs review"],hazardBasis:[]}};
const clean=(v:unknown)=>typeof v==="string"?v.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim():"";
const apiKey=()=>process.env.REGULATIONS_GOV_API_KEY||"DEMO_KEY";
class UpstreamError extends Error{status:number;constructor(status:number){super(`Official Regulations.gov API returned ${status}`);this.status=status}}
const responseCache=new Map<string,{at:number;value:any}>(),inFlight=new Map<string,Promise<any>>();
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function getJson(url:string){const cached=responseCache.get(url);if(cached&&Date.now()-cached.at<CACHE_TTL_MS)return cached.value;const existing=inFlight.get(url);if(existing)return existing;const work=(async()=>{let lastStatus=502;for(let attempt=0;attempt<=MAX_RETRIES;attempt++){const r=await fetch(url,{headers:{Accept:"application/vnd.api+json","User-Agent":"CPSC-Regulatory-Review-Workspace/1.0"},cache:"no-store",signal:AbortSignal.timeout(12_000)});if(r.ok){const value=await r.json();responseCache.set(url,{at:Date.now(),value});return value}lastStatus=r.status;if(!(r.status===429||r.status>=500)||attempt===MAX_RETRIES)throw new UpstreamError(r.status);const retryAfter=Number(r.headers.get("Retry-After"));await wait(Number.isFinite(retryAfter)&&retryAfter>0?retryAfter*1000:500*(2**attempt)+Math.floor(Math.random()*250))}throw new UpstreamError(lastStatus)})();inFlight.set(url,work);try{return await work}finally{inFlight.delete(url)}}
async function getListings(docketId:string,key:string){const listed:any[]=[];let meta:any={};for(let page=1;page<=MAX_LISTING_PAGES;page++){const params=new URLSearchParams({"filter[docketId]":docketId,"page[number]":String(page),"page[size]":String(LISTING_PAGE_SIZE),sort:"-postedDate",api_key:key});const listing=await getJson(`https://api.regulations.gov/v4/comments?${params}`);listed.push(...(listing.data||[]));meta=listing.meta||meta;if(!meta.hasNextPage||page>=Number(meta.totalPages||1))break}return {listed,meta}}
export async function GET(request:NextRequest){
 const docketId=(request.nextUrl.searchParams.get("docketId")||"").trim(),documentId=(request.nextUrl.searchParams.get("documentId")||"").trim();
 if(!/^CPSC-[A-Z0-9-]{4,40}$/i.test(docketId))return NextResponse.json({error:"A valid selected CPSC docket ID is required. The comment-theme matrix cannot run for a record without an official docket identifier.",documentId},{status:422});
 const retrievedAt=new Date().toISOString(),key=apiKey();
 try{
  const {listed,meta}=await getListings(docketId,key);
  const selected=listed.filter((x:any)=>!x.attributes?.withdrawn).slice(0,MAX_COMMENT_DETAILS);
  const details:any[]=[];for(const [index,item] of selected.entries()){try{details.push({item:(await getJson(`https://api.regulations.gov/v4/comments/${encodeURIComponent(item.id)}?api_key=${encodeURIComponent(key)}`)).data,detailRetrieved:true})}catch(e){details.push({item,detailRetrieved:false,detailStatus:e instanceof UpstreamError?e.status:null})}if(index<selected.length-1)await wait(DETAIL_INTERVAL_MS)}
  const comments=details.map((detail:any)=>{const item=detail.item,a=item.attributes||{},text=clean(a.comment),first=clean(a.firstName),last=clean(a.lastName),organization=clean(a.organization),submitterName=[first,last].filter(Boolean).join(" ");return {id:item.id,postedDate:a.postedDate||null,title:clean(a.title)||"Public comment",submitterName:submitterName||null,organization:organization||null,submitterAvailability:submitterName||organization?"published":"unavailable_or_redacted",textAvailable:Boolean(text),text,sourceUrl:`https://www.regulations.gov/comment/${encodeURIComponent(item.id)}`,detailRetrieved:detail.detailRetrieved}});
  const themeMap=new Map<string,any>();for(const t of TAXONOMY)themeMap.set(t.label,{theme:t.label,commentIds:[],supportingCommenters:[],comments:[]});
  let unclassified=0;for(const c of comments){if(!c.textAvailable)continue;const lower=c.text.toLowerCase(),matched=TAXONOMY.filter(t=>t.words.some(w=>lower.includes(w)));if(!matched.length){unclassified++;continue}const hazard=hazardResult(c.text);for(const t of matched){const row=themeMap.get(t.label);row.commentIds.push(c.id);row.supportingCommenters.push({commentId:c.id,submitterName:c.submitterName,organization:c.organization,availability:c.submitterAvailability});row.comments.push({commentId:c.id,postedDate:c.postedDate,excerpt:c.text.slice(0,320),sourceUrl:c.sourceUrl,hazardTags:hazard.hazardTags,hazardBasis:hazard.hazardBasis})}}
  const themes=[...themeMap.values()].filter(x=>x.commentIds.length).map(x=>({...x,count:x.commentIds.length,humanReviewStatus:"unreviewed",hazardTaxonomyVersion:HAZARD_TAXONOMY_VERSION})).sort((a,b)=>b.count-a.count||a.theme.localeCompare(b.theme));
  const total=meta.totalElements??listed.length,textAvailableCount=comments.filter((x:any)=>x.textAvailable).length;
  return NextResponse.json({documentId,docketId,retrievedAt,source:"Regulations.gov API v4 — comments listing and comment-detail endpoints",credentialMode:process.env.REGULATIONS_GOV_API_KEY?"configured_server_key":"shared_public_demo_key",algorithm:ALGORITHM,hazardTaxonomyVersion:HAZARD_TAXONOMY_VERSION,method:"Deterministic disclosed-keyword grouping aggregates accessible official public-comment text into general themes. Hazard domains are assigned only at the individual-comment level using documented whole-word/stem regular-expression matches; evidence terms are disclosed, multiple domains are allowed, and unmatched comments are labeled Unclear/Needs review. Successful official responses are cached for 15 minutes, concurrent duplicate requests are coalesced, and comment-detail requests are paced at approximately one per second. Transient 429/5xx failures use bounded exponential backoff, jitter, and Retry-After when provided. One comment may appear in multiple themes. Submitter labels are copied only from official firstName, lastName, and organization fields.",totalCommentsReported:total,commentsListed:listed.length,commentsDetailed:comments.length,detailRetrievedCount:comments.filter((x:any)=>x.detailRetrieved).length,detailUnavailableCount:comments.filter((x:any)=>!x.detailRetrieved).length,detailRateLimitedCount:details.filter((x:any)=>x.detailStatus===429).length,detailLimit:MAX_COMMENT_DETAILS,textAvailableCount,submitterUnavailableCount:comments.filter((x:any)=>x.submitterAvailability!=="published").length,unclassifiedTextComments:unclassified,themes,comments:comments.map((x:any)=>({id:x.id,postedDate:x.postedDate,title:x.title,submitterName:x.submitterName,organization:x.organization,submitterAvailability:x.submitterAvailability,textAvailable:x.textAvailable,sourceUrl:x.sourceUrl})),limitations:`This run retrieves all non-withdrawn comments reported in the official listing when there are ${MAX_COMMENT_DETAILS} or fewer; larger dockets are capped at ${MAX_COMMENT_DETAILS} newest non-withdrawn comments. It does not analyze attachments, private fields, withdrawn comments, or comments whose text was unavailable. Detail retrieval failures remain explicit and cannot generate tags without text. Theme counts are counts within successfully detailed comments, not docket-wide prevalence. Cached results, request pacing, and bounded backoff reduce repeat traffic; they do not bypass official limits. Pattern grouping is not an agency finding or legal conclusion.`},{headers:{"Cache-Control":"no-store"}});
 }catch(e){const status=e instanceof UpstreamError&&e.status===429?429:502,credentialMode=process.env.REGULATIONS_GOV_API_KEY?"configured_server_key":"shared_public_demo_key",action=status===429?(credentialMode==="shared_public_demo_key"?"The shared public API quota is temporarily exhausted. Retry later; dependable production access requires an administrator to configure REGULATIONS_GOV_API_KEY as a server-side Sites secret.":"The configured server credential was rate-limited. Retry later or have an administrator review its Regulations.gov quota."):"The official service is unavailable. Retry later.";return NextResponse.json({error:`Public comment content could not be retrieved from Regulations.gov. ${e instanceof Error?e.message:"Official service unavailable"}. ${action} No themes or hazard tags were generated or substituted.`,documentId,docketId,retrievedAt,algorithm:ALGORITHM,credentialMode},{status,headers:status===429?{"Retry-After":"60"}:undefined})}
}
